Improving plots
GEMDAT-repos/GEMDAT pull request #177
Opened 2023-10-23 14:05 UTC by v1kko

2023-10-23 14:08 UTC, v1kko commented
![newplot](https://github.com/GEMDAT-repos/GEMDAT/assets/1472570/6c51e2af-5cd7-48f3-8ac7-eb6eb87cdc42) 
![newplot](https://github.com/GEMDAT-repos/GEMDAT/assets/1472570/40f728cf-dff5-4005-94c8-0b9134fd5f84)
![newplot](https://github.com/GEMDAT-repos/GEMDAT/assets/1472570/6453ceb2-7ed0-45a5-9ca1-1a9e1cd5473b)

2023-10-31 09:35 UTC, v1kko commented
@stefsmeets can you have a look at this? 

I have two questions:

- should I remove the old plotting methods, or keep both?
- Are there more plotting routines which should include `n_parts` based error-analysis?

2023-10-31 14:53 UTC, stefsmeets requested changes
Looks good! These plots look way nicer than what we had! I left some comments on the code.

Things that come to mind:
- The dashboard seems to have some caching issues where the plots ar not updated if I play with the toggles and `n_parts`.
- I don't see the jumps and vibrational amplitudes ones in the dashboard.
- Most of the new functions do some pandas work to get the data in a usable format. Does it make sense to return directly from Trajectory/Sites/Transitions etc? Maybe consolidating some of the code in the new plotting functions, and to help separate plotting code from data wrangling code. This makes it more testable as well. And users who want to make their own plots can access the data more easily. Relates a bit to https://github.com/GEMDAT-repos/GEMDAT/issues/32
- Avoid having 2 of the same function in the same submodule. Having both `displacement_per_element` and `displacement_per_element2` makes it a bit confusing. We could have 2 submodules `gemdat/plots/matplotlib` and `gemdat/plots/plotly` to separate them, and only expose in our api. So that `from gemdat import plots; plots.displacement_per_element(...)` points to the plotly one if available.
- Matplotlib functions are way simpler, could we keep those around as the reference implemtation and for testing correctness? I can't find any simple workflow for testing plotly plots.

To address your questions:
1. Yes, until we find a way to test the plotly plots.
2. I don't know, they can easily be added later 😅

As a side note, I also think it becomes time to think about refactoring the dashboard, and make separate pages for each group of plots. It becomes a bit cluttered in my view and unfortunately you can't get the tab state, so you must have a checkbox to enable rdf, density, n_parts, etc.

2023-10-31 14:53 UTC, stefsmeets commented on src/gemdat/plots/_vibration.py
> +    minamp = -maxamp
🤯

Would it be possible to refactor this without lambda and make it easier to read?

2023-10-31 14:53 UTC, stefsmeets commented on src/gemdat/plots/_vibration.py
> +    minamp = -maxamp
```suggestion
    max_amp = max(max(metric) for metric in metrics))
    min_amp = min(min(metric) for metric in metrics))
    
    max_amp = max(abs(min_amp), max_amp)
    min_amp = -max_val
```

2023-10-31 14:53 UTC, stefsmeets commented on src/gemdat/plots/_vibration.py
> +        fig = px.bar(df, x='amplitude', y='count', error_y='std')
```suggestion
    error_y = 'std' if n_parts else None
    fig = px.bar(df, x='amplitude', y='count', error_y=error_y)
```

2023-10-31 14:53 UTC, stefsmeets commented on src/gemdat/plots/_vibration.py
> +        xaxis_title='Amplitude (Angstrom)',
```suggestion
        xaxis_title='Amplitude (Ångstrom)',
```

2023-10-31 14:53 UTC, stefsmeets commented on src/gemdat/trajectory.py
> +    def split(self, n_parts: int) -> List[Trajectory]:
```suggestion
    def split(self, n_parts: int) -> list[Trajectory]:
```

2023-10-31 14:53 UTC, stefsmeets commented on src/gemdat/trajectory.py
> +from typing import Collection, List, Optional
You can use the built-in list type since 3.9.

```suggestion
from typing import Collection, Optional
```

2023-10-31 14:53 UTC, stefsmeets commented on src/gemdat/trajectory.py
> +        ]
Would be nice to use pairwire here: https://docs.python.org/3/library/itertools.html#itertools.pairwise

```suggestion
        interval = np.linspace(0, len(self) - 1, n_parts + 1, dtype=int)
        subtrajectories = [
            self[start:stop] for start, stop in pairwise(interval)
        ]
```

2023-11-03 12:49 UTC, v1kko commented on src/gemdat/plots/_jumps.py
> +        fig = px.bar(df, x='time', y='count', color='specie')
That causes error bars to show (even if error_y is none) so better to leave it as is

2023-11-03 12:50 UTC, v1kko commented on src/gemdat/plots/_jumps.py
> +                      yaxis_title='Number of jumps')
yes

2023-11-03 12:52 UTC, v1kko commented on src/gemdat/plots/_vibration.py
> +        fig = px.bar(df, x='amplitude', y='count', error_y='std')
doesnt work unfortunately (error bars will still show up)

2023-11-03 14:20 UTC, merged