Add option to select MSD algorithm
GEMDAT-repos/GEMDAT pull request #291
Opened 2024-03-20 15:47 UTC by SCiarella

This PR closes #285.

2024-03-25 07:47 UTC, SCiarella commented
This PR also closes #290

2024-03-26 15:54 UTC, stefsmeets commented
Can you say a little bit what this PR does?
What is the effect of the jit on the performance?

2024-03-27 08:02 UTC, SCiarella commented
The goal of this PR is to allow the user to select the desired algorithm to measure the MSD and the MSAD. The same choice is made available for the plotting functions in `gemdat.plot`.

For the MSD the user can select how many 'starting points' to use via `nstarts`. The default is to use **all** the possible starting points, in which case GEMDAT will rely on `_fft_mean_squared_displacement`. If the user selects a specific value of `nstarts`, then it is not possible to use the FFT method, so I have implemented `_direct_mean_squared_displacement`. However, the direct method become extremely slow for large values of `nstarts`, so I used jit compilation via numba, which makes the code up to 100 times faster (depending on the value of `nstarts`).  The jit compilation requires `_direct_mean_squared_displacement` to be outside of `Trajectory`.

The same approach has been implemented for the MSAD (and `plots.unit_vector_autocorrelation`), where the user can select between the FFT calculation or a direct one. The difference is that instead of `nstarts`, the MSAD is parallelized over `n_tgrid` which corresponds to the specific values of $t$ where the MSAD should be measured (the MSAD always assumes `nstarts=all`).

Additionally, this PR also addresses some minor improvements, like implementing the time units on the msd plots, normalizing the autocorrelation and plotting the error.

2024-03-27 09:15 UTC, stefsmeets requested changes
Hi @SCiarella just made a first pass. Plots look great as always 🚀

I'm not entirely convinced that we need numba over some vectorized numpy code (see comments).

I also do not understand why we need `nstarts` as an argument it adds, for me it complicates things. What would be the most optimal way to calculate the msd? That should be the one we support.

Finally, can you add some unit tests (not integration) for the new code?

2024-03-29 09:34 UTC, SCiarella commented
Update:

After the optimization happening in this PR, GEMDAT will **support only the most efficient methods** for the MSD and the MSAD, which are the **FFT** methods.

The results of a comparison available [here](https://github.com/GEMDAT-repos/gemdat-notebooks/blob/main/msd.ipynb) show that:
(1) the MSD direct method converges to the FFT results 
![image](https://github.com/GEMDAT-repos/GEMDAT/assets/58949181/2f93c80e-1409-4f6a-9f6d-b775d7ea6c74)
(2) the FFT method for MSD is faster
![image](https://github.com/GEMDAT-repos/GEMDAT/assets/58949181/e1c7c924-c862-499c-bcee-5bbb5f2add01)

(3) the MSAD direct method converges toward the FFT results
![image](https://github.com/GEMDAT-repos/GEMDAT/assets/58949181/740195b8-ad1f-49c6-b521-f6409ebf742d)
(4) the FFT method for MSAD is faster
![image](https://github.com/GEMDAT-repos/GEMDAT/assets/58949181/785d82c8-2ac9-41e4-bcd3-dab5af5dd194)

2024-03-29 09:35 UTC, SCiarella commented
This PR closes #274

2024-03-29 09:37 UTC, SCiarella commented on src/gemdat/rotations.py
> +        msad = msad.transpose(1, 0)
This is not relevant anymore, since we only support the FFT method now

2024-03-29 09:38 UTC, SCiarella commented on src/gemdat/rotations.py
> +@njit(parallel=True)
Removed

2024-03-29 09:43 UTC, SCiarella commented on src/gemdat/rotations.py
> +def mean_squared_angular_displacement(
the input trajectory for `mean_squared_angular_displacement` is a unit vector trajectory that gets returned from `Orientations` directly as a np.ndarray. We should address the output of `Orientations` in a future PR.

2024-03-29 10:00 UTC, SCiarella commented on src/gemdat/trajectory.py
> +    unwrapped_coords -= corrections
Thanks! It is exactly the same thing! I have removed `_unwrap_pbc`

2024-04-03 13:39 UTC, stefsmeets approved these changes
Looks good to me!

2024-04-03 13:39 UTC, merged